Repository openmodelingfoundation/openmodelingfoundation.github.io, pull requests merged in 2021-12, with the labels that each got.

#334 Corrected heading hierarchy in activities section
  content/en/governance/charter/_index.md
Labels: governance, organization

#332 clarification about voting quorum and intent to remain a member
  content/en/governance/charter/_index.md
Labels: governance

#357 revise vision statement
  content/en/governance/charter/_index.md
Labels: ACTION: Vote

#364 minor revision to organizational structure goals
  content/en/governance/charter/_index.md
Labels: ACTION: Vote

#369 revise OMF member definition
  content/en/governance/charter/_index.md
Labels: ACTION: Vote

#371 add values to member responsiblities
  content/en/governance/charter/_index.md
Labels: ACTION: Vote

#373 revise voting rights and responsibilities.md
  content/en/governance/charter/_index.md
Labels: ACTION: Vote

#375 rearrange values statement sections
  content/en/about/community.md
  content/en/about/history.md
  content/en/about/values.md
Labels: governance, ACTION: Vote

#378 update voting procedures
  content/en/governance/charter/_index.md
Labels: ACTION: Vote

#380 add values into charter
  content/en/governance/charter/_index.md
Labels: ACTION: Vote

#385 update and approve AECS
  content/en/governance/charter/_index.md
Labels: ACTION: Vote

#388 Revising working group description
  content/en/governance/charter/_index.md
Labels: ACTION: Vote

#390 updated charter title
  content/en/governance/charter/_index.md
Labels: governance, OMF site content
